## Map `SOX4` Targets to Transcripts

In [1]:
%%bash

bedtools="/project/PlatigLab/software/bedtools-v2.31.1/bin/bedtools"
ucsc_gene_file='../../../inputs/resource_files/mm10_gencode_vm23_knownGene.bed'
input_file='../3_bedtools_intersect/outputs/MA0867.2.upstream_750.bed.gz'
output_file='all_SOX4_targets_750_upstream.bed'

gunzip -c ${input_file} | grep SOX4 | $bedtools window -a $ucsc_gene_file -b stdin -l 5000 -r 0 -sw > $output_file

gzip $output_file

## Load `SOX4` File & Transcripts-to-Genes Mapping File

In [2]:
import polars as pl
_=pl.Config.set_tbl_rows(1000)



from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
mapping_file = pl.read_csv("../../../inputs/mouse_transcripts_genes_mapping/mm10_genes_and_transcripts.tsv", separator="\t")
mapping_file.head()

shape: (5, 3)
┌────────────────────┬──────────────────────┬───────────┐
│ Gene stable ID     ┆ Transcript stable ID ┆ Gene name │
│ ---                ┆ ---                  ┆ ---       │
│ str                ┆ str                  ┆ str       │
╞════════════════════╪══════════════════════╪═══════════╡
│ ENSMUSG00000064370 ┆ ENSMUST00000082421   ┆ mt-Cytb   │
│ ENSMUSG00000064368 ┆ ENSMUST00000082419   ┆ mt-Nd6    │
│ ENSMUSG00000064367 ┆ ENSMUST00000082418   ┆ mt-Nd5    │
│ ENSMUSG00000064363 ┆ ENSMUST00000082414   ┆ mt-Nd4    │
│ ENSMUSG00000065947 ┆ ENSMUST00000084013   ┆ mt-Nd4l   │
└────────────────────┴──────────────────────┴───────────┘

In [4]:
sox4_data = pl.read_csv("./all_SOX4_targets_750_upstream.bed.gz", separator="\t", has_header=False)

sox4_data = sox4_data.filter(pl.col('column_17') > 950)
sox4_data = sox4_data.with_columns(
    pl.col("column_4").str.split(".").list.get(0).alias("column_4")
)

sox4_data.shape
sox4_data.head()

(193263, 28)

shape: (5, 28)
┌──────────┬──────────┬──────────┬─────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ column_1 ┆ column_2 ┆ column_3 ┆ column_4    ┆ … ┆ column_25 ┆ column_26 ┆ column_27 ┆ column_28 │
│ ---      ┆ ---      ┆ ---      ┆ ---         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str      ┆ i64      ┆ i64      ┆ str         ┆   ┆ str       ┆ i64       ┆ i64       ┆ str       │
╞══════════╪══════════╪══════════╪═════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ chr1     ┆ 3214481  ┆ 3671498  ┆ ENSMUST0000 ┆ … ┆ -         ┆ 3319505   ┆ 3319506   ┆ 255,255,0 │
│          ┆          ┆          ┆ 0070533     ┆   ┆           ┆           ┆           ┆           │
│ chr1     ┆ 3214481  ┆ 3671498  ┆ ENSMUST0000 ┆ … ┆ -         ┆ 3319505   ┆ 3319506   ┆ 255,255,0 │
│          ┆          ┆          ┆ 0070533     ┆   ┆           ┆           ┆           ┆           │
│ chr1     ┆ 3214481  ┆ 3671498  ┆ ENSMUST0000 ┆ … ┆ -         ┆ 3319505   ┆ 3319506   ┆ 255,255,0 │
│          ┆          ┆          ┆ 0070533     ┆   ┆           ┆           ┆           ┆           │
│ chr1     ┆ 4292980  ┆ 4409187  ┆ ENSMUST0000 ┆ … ┆ -         ┆ 4409231   ┆ 4409232   ┆ 255,255,0 │
│          ┆          ┆          ┆ 0194992     ┆   ┆           ┆           ┆           ┆           │
│ chr1     ┆ 4292980  ┆ 4409187  ┆ ENSMUST0000 ┆ … ┆ -         ┆ 4409261   ┆ 4409262   ┆ 255,255,0 │
│          ┆          ┆          ┆ 0194992     ┆   ┆           ┆           ┆           ┆           │
└──────────┴──────────┴──────────┴─────────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Filter `SOX4` Results to those Targetting Genes Sunny Cares About

In [5]:
sunny_selected_genes = ["Nr2f1", "Srebf2", "Fads2", "Hipk2", "Ttl", "Rgcc", "Sqle", "Scd2"]
sunny_selected_genes_lower = [gene.lower() for gene in sunny_selected_genes]

sunny_selected_genes_lower

['nr2f1', 'srebf2', 'fads2', 'hipk2', 'ttl', 'rgcc', 'sqle', 'scd2']

In [6]:
mapping_file_subset = mapping_file.filter(
    pl.col("Gene name").str.to_lowercase().is_in(sunny_selected_genes_lower)
)
    
mapping_file_subset

shape: (33, 3)
┌────────────────────┬──────────────────────┬───────────┐
│ Gene stable ID     ┆ Transcript stable ID ┆ Gene name │
│ ---                ┆ ---                  ┆ ---       │
│ str                ┆ str                  ┆ str       │
╞════════════════════╪══════════════════════╪═══════════╡
│ ENSMUSG00000022018 ┆ ENSMUST00000022595   ┆ Rgcc      │
│ ENSMUSG00000022463 ┆ ENSMUST00000023100   ┆ Srebf2    │
│ ENSMUSG00000022463 ┆ ENSMUST00000229336   ┆ Srebf2    │
│ ENSMUSG00000022463 ┆ ENSMUST00000231065   ┆ Srebf2    │
│ ENSMUSG00000022463 ┆ ENSMUST00000230105   ┆ Srebf2    │
│ ENSMUSG00000022463 ┆ ENSMUST00000229009   ┆ Srebf2    │
│ ENSMUSG00000022463 ┆ ENSMUST00000229518   ┆ Srebf2    │
│ ENSMUSG00000022463 ┆ ENSMUST00000230955   ┆ Srebf2    │
│ ENSMUSG00000022351 ┆ ENSMUST00000162142   ┆ Sqle      │
│ ENSMUSG00000022351 ┆ ENSMUST00000022977   ┆ Sqle      │
│ ENSMUSG00000022351 ┆ ENSMUST00000100640   ┆ Sqle      │
│ ENSMUSG00000022351 ┆ ENSMUST00000161953   ┆ Sqle      │
│ ENSMUSG00000061436 ┆ ENSMUST00000161779   ┆ Hipk2     │
│ ENSMUSG00000061436 ┆ ENSMUST00000160962   ┆ Hipk2     │
│ ENSMUSG00000061436 ┆ ENSMUST00000162359   ┆ Hipk2     │
│ ENSMUSG00000061436 ┆ ENSMUST00000160360   ┆ Hipk2     │
│ ENSMUSG00000061436 ┆ ENSMUST00000159307   ┆ Hipk2     │
│ ENSMUSG00000061436 ┆ ENSMUST00000159894   ┆ Hipk2     │
│ ENSMUSG00000061436 ┆ ENSMUST00000114855   ┆ Hipk2     │
│ ENSMUSG00000025203 ┆ ENSMUST00000026221   ┆ Scd2      │
│ ENSMUSG00000025203 ┆ ENSMUST00000237039   ┆ Scd2      │
│ ENSMUSG00000024665 ┆ ENSMUST00000025567   ┆ Fads2     │
│ ENSMUSG00000024665 ┆ ENSMUST00000238023   ┆ Fads2     │
│ ENSMUSG00000024665 ┆ ENSMUST00000235937   ┆ Fads2     │
│ ENSMUSG00000069171 ┆ ENSMUST00000091458   ┆ Nr2f1     │
│ ENSMUSG00000069171 ┆ ENSMUST00000150498   ┆ Nr2f1     │
│ ENSMUSG00000069171 ┆ ENSMUST00000127137   ┆ Nr2f1     │
│ ENSMUSG00000069171 ┆ ENSMUST00000125176   ┆ Nr2f1     │
│ ENSMUSG00000069171 ┆ ENSMUST00000135284   ┆ Nr2f1     │
│ ENSMUSG00000069171 ┆ ENSMUST00000224798   ┆ Nr2f1     │
│ ENSMUSG00000027394 ┆ ENSMUST00000035812   ┆ Ttl       │
│ ENSMUSG00000027394 ┆ ENSMUST00000144730   ┆ Ttl       │
│ ENSMUSG00000027394 ┆ ENSMUST00000144120   ┆ Ttl       │
└────────────────────┴──────────────────────┴───────────┘

In [7]:
joined = mapping_file_subset.join(
    sox4_data, left_on="Transcript stable ID", right_on="column_4", how="inner"
).sort("Gene name")

for gene in sunny_selected_genes_lower:
    assert joined.filter(pl.col("Gene name").str.to_lowercase() == gene).height > 0, f"No entry found for gene: {gene}"

joined.shape
joined.head()

(106, 30)

shape: (5, 30)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Gene      ┆ Transcrip ┆ Gene name ┆ column_1 ┆ … ┆ column_25 ┆ column_26 ┆ column_27 ┆ column_28 │
│ stable ID ┆ t stable  ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ ---       ┆ ID        ┆ str       ┆ str      ┆   ┆ str       ┆ i64       ┆ i64       ┆ str       │
│ str       ┆ ---       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆ str       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19    ┆ … ┆ +         ┆ 10077448  ┆ 10077449  ┆ 255,255,0 │
│ 000024665 ┆ 000235937 ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19    ┆ … ┆ -         ┆ 10088981  ┆ 10088982  ┆ 255,255,0 │
│ 000024665 ┆ 000235937 ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19    ┆ … ┆ -         ┆ 10064173  ┆ 10064174  ┆ 255,255,0 │
│ 000024665 ┆ 000025567 ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19    ┆ … ┆ +         ┆ 10077448  ┆ 10077449  ┆ 255,255,0 │
│ 000024665 ┆ 000025567 ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19    ┆ … ┆ -         ┆ 10088981  ┆ 10088982  ┆ 255,255,0 │
│ 000024665 ┆ 000025567 ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Rename Columns and Output Data

In [8]:
column_renaming_map = {
    'column_1': 'START OF GENE WINDOW INFO',  
    'column_13': 'START OF MOTIF LOCATION', 
    'column_14': "Motif Start", 
    'column_15': 'Motif End', 
    'column_17': 'Relative Score', 
    'column_20': 'START OF TSS INFO'
    
}

renamed = joined.rename(column_renaming_map)
renamed

shape: (106, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Gene      ┆ Transcrip ┆ Gene name ┆ START OF  ┆ … ┆ column_25 ┆ column_26 ┆ column_27 ┆ column_2 │
│ stable ID ┆ t stable  ┆ ---       ┆ GENE      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 8        │
│ ---       ┆ ID        ┆ str       ┆ WINDOW    ┆   ┆ str       ┆ i64       ┆ i64       ┆ ---      │
│ str       ┆ ---       ┆           ┆ INFO      ┆   ┆           ┆           ┆           ┆ str      │
│           ┆ str       ┆           ┆ ---       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19     ┆ … ┆ +         ┆ 10077448  ┆ 10077449  ┆ 255,255, │
│ 000024665 ┆ 000235937 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19     ┆ … ┆ -         ┆ 10088981  ┆ 10088982  ┆ 255,255, │
│ 000024665 ┆ 000235937 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19     ┆ … ┆ -         ┆ 10064173  ┆ 10064174  ┆ 255,255, │
│ 000024665 ┆ 000025567 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19     ┆ … ┆ +         ┆ 10077448  ┆ 10077449  ┆ 255,255, │
│ 000024665 ┆ 000025567 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19     ┆ … ┆ -         ┆ 10088981  ┆ 10088982  ┆ 255,255, │
│ 000024665 ┆ 000025567 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19     ┆ … ┆ -         ┆ 10101516  ┆ 10101517  ┆ 255,255, │
│ 000024665 ┆ 000025567 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19     ┆ … ┆ -         ┆ 10101555  ┆ 10101556  ┆ 255,255, │
│ 000024665 ┆ 000025567 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19     ┆ … ┆ -         ┆ 10101738  ┆ 10101739  ┆ 255,255, │
│ 000024665 ┆ 000025567 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19     ┆ … ┆ -         ┆ 10101814  ┆ 10101815  ┆ 255,255, │
│ 000024665 ┆ 000025567 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Fads2     ┆ chr19     ┆ … ┆ -         ┆ 10101835  ┆ 10101836  ┆ 255,255, │
│ 000024665 ┆ 000025567 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38737475  ┆ 38737476  ┆ 255,255, │
│ 000061436 ┆ 000161779 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38745753  ┆ 38745754  ┆ 255,255, │
│ 000061436 ┆ 000161779 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38782280  ┆ 38782281  ┆ 255,255, │
│ 000061436 ┆ 000161779 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ +         ┆ 38874807  ┆ 38874808  ┆ 255,255, │
│ 000061436 ┆ 000161779 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ +         ┆ 38874807  ┆ 38874808  ┆ 255,255, │
│ 000061436 ┆ 000161779 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38876508  ┆ 38876509  ┆ 255,255, │
│ 000061436 ┆ 000161779 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38876523  ┆ 38876524  ┆ 255,255, │
│ 000061436 ┆ 000161779 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38876536  ┆ 38876537  ┆ 255,255, │
│ 000061436 ┆ 000161779 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38737475  ┆ 38737476  ┆ 255,255, │
│ 000061436 ┆ 000160962 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38745753  ┆ 38745754  ┆ 255,255, │
│ 000061436 ┆ 000160962 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38782280  ┆ 38782281  ┆ 255,255, │
│ 000061436 ┆ 000160962 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38737475  ┆ 38737476  ┆ 255,255, │
│ 000061436 ┆ 000162359 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38745753  ┆ 38745754  ┆ 255,255, │
│ 000061436 ┆ 000162359 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38782280  ┆ 38782281  ┆ 255,255, │
│ 000061436 ┆ 000162359 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ +         ┆ 38874807  ┆ 38874808  ┆ 255,255, │
│ 000061436 ┆ 000162359 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ +         ┆ 38874807  ┆ 38874808  ┆ 255,255, │
│ 000061436 ┆ 000162359 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38876508  ┆ 38876509  ┆ 255,255, │
│ 000061436 ┆ 000162359 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38876523  ┆ 38876524  ┆ 255,255, │
│ 000061436 ┆ 000162359 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38876536  ┆ 38876537  ┆ 255,255, │
│ 000061436 ┆ 000162359 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38737475  ┆ 38737476  ┆ 255,255, │
│ 000061436 ┆ 000160360 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38745753  ┆ 38745754  ┆ 255,255, │
│ 000061436 ┆ 000160360 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38782280  ┆ 38782281  ┆ 255,255, │
│ 000061436 ┆ 000160360 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ +         ┆ 38874807  ┆ 38874808  ┆ 255,255, │
│ 000061436 ┆ 000160360 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ +         ┆ 38874807  ┆ 38874808  ┆ 255,255, │
│ 000061436 ┆ 000160360 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38876508  ┆ 38876509  ┆ 255,255, │
│ 000061436 ┆ 000160360 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38876523  ┆ 38876524  ┆ 255,255, │
│ 000061436 ┆ 000160360 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38876536  ┆ 38876537  ┆ 255,255, │
│ 000061436 ┆ 000160360 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38737475  ┆ 38737476  ┆ 255,255, │
│ 000061436 ┆ 000159307 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38745753  ┆ 38745754  ┆ 255,255, │
│ 000061436 ┆ 000159307 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38745753  ┆ 38745754  ┆ 255,255, │
│ 000061436 ┆ 000159894 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Hipk2     ┆ chr6      ┆ … ┆ -         ┆ 38782280  ┆ 38782281  ┆ 255,255, │
│ 000061436 ┆ 000159894 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Nr2f1     ┆ chr13     ┆ … ┆ -         ┆ 78196433  ┆ 78196434  ┆ 255,255, │
│ 000069171 ┆ 000091458 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Nr2f1     ┆ chr13     ┆ … ┆ -         ┆ 78196481  ┆ 78196482  ┆ 255,255, │
│ 000069171 ┆ 000091458 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Nr2f1     ┆ chr13     ┆ … ┆ -         ┆ 78196433  ┆ 78196434  ┆ 255,255, │
│ 000069171 ┆ 000150498 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Nr2f1     ┆ chr13     ┆ … ┆ -         ┆ 78196481  ┆ 78196482  ┆ 255,255, │
│ 000069171 ┆ 000150498 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Nr2f1     ┆ chr13     ┆ … ┆ -         ┆ 78196433  ┆ 78196434  ┆ 255,255, │
│ 000069171 ┆ 000127137 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Nr2f1     ┆ chr13     ┆ … ┆ -         ┆ 78196481  ┆ 78196482  ┆ 255,255, │
│ 000069171 ┆ 000127137 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Nr2f1     ┆ chr13     ┆ … ┆ -         ┆ 78196433  ┆ 78196434  ┆ 255,255, │
│ 000069171 ┆ 000125176 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Nr2f1     ┆ chr13     ┆ … ┆ -         ┆ 78196481  ┆ 78196482  ┆ 255,255, │
│ 000069171 ┆ 000125176 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Nr2f1     ┆ chr13     ┆ … ┆ -         ┆ 78196433  ┆ 78196434  ┆ 255,255, │
│ 000069171 ┆ 000224798 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Nr2f1     ┆ chr13     ┆ … ┆ -         ┆ 78196481  ┆ 78196482  ┆ 255,255, │
│ 000069171 ┆ 000224798 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Rgcc      ┆ chr14     ┆ … ┆ -         ┆ 79291994  ┆ 79291995  ┆ 255,255, │
│ 000022018 ┆ 000022595 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44293455  ┆ 44293456  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294022  ┆ 44294023  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294086  ┆ 44294087  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294145  ┆ 44294146  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294163  ┆ 44294164  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294199  ┆ 44294200  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294239  ┆ 44294240  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294257  ┆ 44294258  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294269  ┆ 44294270  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294300  ┆ 44294301  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44298093  ┆ 44298094  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44301287  ┆ 44301288  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44301374  ┆ 44301375  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44301287  ┆ 44301288  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44301374  ┆ 44301375  ┆ 255,255, │
│ 000025203 ┆ 000237039 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44293455  ┆ 44293456  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294022  ┆ 44294023  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294086  ┆ 44294087  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294145  ┆ 44294146  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294163  ┆ 44294164  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294199  ┆ 44294200  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294239  ┆ 44294240  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294257  ┆ 44294258  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294269  ┆ 44294270  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44294300  ┆ 44294301  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44298093  ┆ 44298094  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44301287  ┆ 44301288  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44301374  ┆ 44301375  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44301287  ┆ 44301288  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Scd2      ┆ chr19     ┆ … ┆ +         ┆ 44301374  ┆ 44301375  ┆ 255,255, │
│ 000025203 ┆ 000026221 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Sqle      ┆ chr15     ┆ … ┆ +         ┆ 59323627  ┆ 59323628  ┆ 255,255, │
│ 000022351 ┆ 000162142 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Sqle      ┆ chr15     ┆ … ┆ +         ┆ 59323627  ┆ 59323628  ┆ 255,255, │
│ 000022351 ┆ 000162142 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Sqle      ┆ chr15     ┆ … ┆ +         ┆ 59323627  ┆ 59323628  ┆ 255,255, │
│ 000022351 ┆ 000022977 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Sqle      ┆ chr15     ┆ … ┆ +         ┆ 59323627  ┆ 59323628  ┆ 255,255, │
│ 000022351 ┆ 000022977 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Sqle      ┆ chr15     ┆ … ┆ +         ┆ 59323627  ┆ 59323628  ┆ 255,255, │
│ 000022351 ┆ 000100640 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Sqle      ┆ chr15     ┆ … ┆ +         ┆ 59323627  ┆ 59323628  ┆ 255,255, │
│ 000022351 ┆ 000100640 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Sqle      ┆ chr15     ┆ … ┆ +         ┆ 59323627  ┆ 59323628  ┆ 255,255, │
│ 000022351 ┆ 000161953 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Sqle      ┆ chr15     ┆ … ┆ +         ┆ 59323627  ┆ 59323628  ┆ 255,255, │
│ 000022351 ┆ 000161953 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Srebf2    ┆ chr15     ┆ … ┆ -         ┆ 82147495  ┆ 82147496  ┆ 255,255, │
│ 000022463 ┆ 000023100 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Srebf2    ┆ chr15     ┆ … ┆ -         ┆ 82147517  ┆ 82147518  ┆ 255,255, │
│ 000022463 ┆ 000023100 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Srebf2    ┆ chr15     ┆ … ┆ -         ┆ 82147495  ┆ 82147496  ┆ 255,255, │
│ 000022463 ┆ 000229336 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Srebf2    ┆ chr15     ┆ … ┆ -         ┆ 82147517  ┆ 82147518  ┆ 255,255, │
│ 000022463 ┆ 000229336 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ ENSMUSG00 ┆ ENSMUST00 ┆ Srebf2    ┆ chr15     ┆ … ┆ -         ┆ 82147495  ┆ 82147496  ┆ 255,255, │

In [9]:
renamed.write_csv('sunny_selected_genes_motif_locations.csv')