## Gene Ontology Analyses of `Sox4` Targets

## Purpose: 

For each parameter combination, take all `Sox4` target genes predicted from `JASPAR` and run `GO` analysis.
Output tables and summary results.

## Packages and Options

In [1]:
import networkx, pickle, glob, os

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from goatools.obo_parser import GODag
from goatools.goea.go_enrichment_ns import GOEnrichmentStudyNS
from goatools.base import download_go_basic_obo

import pandas as pd
pd.set_option('display.max_rows', 1000000)
pd.set_option('display.max_columns', 1000000)
pd.set_option('display.max_colwidth', 10000000)

## Load Gene Lists 

Load lists of genes that are `Sox4` targets per each parameter combination

In [2]:
sox4_target_dict = {}

for file in glob.glob("../../../../outputs/pickled_networks/differential_expression_tf_networks/*"): 
    
    network = pickle.load(open(file, 'rb'))
    
    sox4_target_dict[file.split("/")[-1].split(".")[0]] =  [edge_pair[1] for edge_pair in network.out_edges(["sox4"])]

## Setup for `GOATOOLS` (Tool for `GO` Analysis)

In [3]:
download_go_basic_obo()

  EXISTS: go-basic.obo

'go-basic.obo'

In [4]:
# file for population (protein-coding genes)
protein_coding_genes = []

with open("../../../../inputs/goatools_input/population.txt", 'r') as in_file: 
    for line in in_file: 
        protein_coding_genes.append(line.strip("\n"))
        
# file for gene ontology associations
associations = pickle.load(open("../../../../inputs/goatools_input/mouse/gene_ontology_associations.pkl", 'rb'))

## Run `GO` Analysis

In [5]:
for param_combo in sox4_target_dict: 
    
    # initialize object with population, associations, and GO DAG
    enrichment_analysis_obj = GOEnrichmentStudyNS(

        protein_coding_genes,
        associations, 
        GODag("go-basic.obo"), 

        # not propagating counts to parents of GO terms 
        propagate_counts = False, 
        methods = ["fdr_bh"]
    )
    
    results = enrichment_analysis_obj.run_study(
        sox4_target_dict[param_combo]
    )
    
    enrichment_analysis_obj.wr_tsv(param_combo, results)

# remove the OBO file
os.remove("go-basic.obo")

go-basic.obo: fmt(1.2) rel(2024-01-17) 45,869 Terms

Load BP Ontology Enrichment Analysis ...
 85% 18,620 of 21,965 population items found in association

Load CC Ontology Enrichment Analysis ...
 85% 18,761 of 21,965 population items found in association

Load MF Ontology Enrichment Analysis ...
 85% 18,703 of 21,965 population items found in association

Runing BP Ontology Analysis: current study set of 81 IDs.
 98%     79 of     81 study items found in association
100%     81 of     81 study items found in population(21965)
Calculating 12,503 uncorrected p-values using fisher_scipy_stats
  12,503 terms are associated with 18,612 of 21,965 population items
   1,094 terms are associated with     79 of     81 study items
  METHOD fdr_bh:
      11 GO terms found significant (< 0.05=alpha) ( 11 enriched +   0 purified): statsmodels fdr_bh
      25 study items associated with significant GO IDs (enriched)
       0 study items associated with significant GO IDs (purified)

Runing CC Ontology Analysis: current study set of 81 IDs.
 99%     80 of     81 study items found in association
100%     81 of     81 study items found in population(21965)
Calculating 1,809 uncorrected p-values using fisher_scipy_stats
   1,809 terms are associated with 18,761 of 21,965 population items
     175 terms are associated with     80 of     81 study items
  METHOD fdr_bh:
       3 GO terms found significant (< 0.05=alpha) (  3 enriched +   0 purified): statsmodels fdr_bh
      57 study items associated with significant GO IDs (enriched)
       0 study items associated with significant GO IDs (purified)

Runing MF Ontology Analysis: current study set of 81 IDs.
 98%     79 of     81 study items found in association
100%     81 of     81 study items found in population(21965)
Calculating 4,565 uncorrected p-values using fisher_scipy_stats
   4,565 terms are associated with 18,703 of 21,965 population items
     330 terms are associated with     79 of     81 study items
  METHOD fdr_bh:
       2 GO terms found significant (< 0.05=alpha) (  2 enriched +   0 purified): statsmodels fdr_bh
       8 study items associated with significant GO IDs (enriched)
       0 study items associated with significant GO IDs (purified)
  18877 items WROTE: upstream_5000_score_990
go-basic.obo: fmt(1.2) rel(2024-01-17) 45,869 Terms

Load BP Ontology Enrichment Analysis ...
 85% 18,620 of 21,965 population items found in association

Load CC Ontology Enrichment Analysis ...
 85% 18,761 of 21,965 population items found in association

Load MF Ontology Enrichment Analysis ...
 85% 18,703 of 21,965 population items found in association

Runing BP Ontology Analysis: current study set of 245 IDs.
 97%    237 of    245 study items found in association
100%    245 of    245 study items found in population(21965)
Calculating 12,503 uncorrected p-values using fisher_scipy_stats
  12,503 terms are associated with 18,612 of 21,965 population items
   2,146 terms are associated with    237 of    245 study items
  METHOD fdr_bh:
      34 GO terms found significant (< 0.05=alpha) ( 33 enriched +   1 purified): statsmodels fdr_bh
     131 study items associated with significant GO IDs (enriched)
      11 study items associated with significant GO IDs (purified)

Runing CC Ontology Analysis: current study set of 245 IDs.
 98%    240 of    245 study items found in association
100%    245 of    245 study items found in population(21965)
Calculating 1,809 uncorrected p-values using fisher_scipy_stats
   1,809 terms are associated with 18,761 of 21,965 population items
     303 terms are associated with    240 of    245 study items
  METHOD fdr_bh:
      21 GO terms found significant (< 0.05=alpha) ( 20 enriched +   1 purified): statsmodels fdr_bh
     170 study items associated with significant GO IDs (enriched)
       8 study items associated with significant GO IDs (purified)

Runing MF Ontology Analysis: current study set of 245 IDs.
 98%    241 of    245 study items found in association
100%    245 of    245 study items found in population(21965)
Calculating 4,565 uncorrected p-values using fisher_scipy_stats
   4,565 terms are associated with 18,703 of 21,965 population items
     556 terms are associated with    241 of    245 study items
  METHOD fdr_bh:
      28 GO terms found significant (< 0.05=alpha) ( 27 enriched +   1 purified): statsmodels fdr_bh
     188 study items associated with significant GO IDs (enriched)
      19 study items associated with significant GO IDs (purified)
  18877 items WROTE: upstream_2500_score_950
go-basic.obo: fmt(1.2) rel(2024-01-17) 45,869 Terms

Load BP Ontology Enrichment Analysis ...
 85% 18,620 of 21,965 population items found in association

Load CC Ontology Enrichment Analysis ...
 85% 18,761 of 21,965 population items found in association

Load MF Ontology Enrichment Analysis ...
 85% 18,703 of 21,965 population items found in association

Runing BP Ontology Analysis: current study set of 284 IDs.
 96%    274 of    284 study items found in association
100%    284 of    284 study items found in population(21965)
Calculating 12,503 uncorrected p-values using fisher_scipy_stats
  12,503 terms are associated with 18,612 of 21,965 population items
   2,299 terms are associated with    274 of    284 study items
  METHOD fdr_bh:
      72 GO terms found significant (< 0.05=alpha) ( 71 enriched +   1 purified): statsmodels fdr_bh
     171 study items associated with significant GO IDs (enriched)
      14 study items associated with significant GO IDs (purified)

Runing CC Ontology Analysis: current study set of 284 IDs.
 97%    276 of    284 study items found in association
100%    284 of    284 study items found in population(21965)
Calculating 1,809 uncorrected p-values using fisher_scipy_stats
   1,809 terms are associated with 18,761 of 21,965 population items
     321 terms are associated with    276 of    284 study items
  METHOD fdr_bh:
      26 GO terms found significant (< 0.05=alpha) ( 25 enriched +   1 purified): statsmodels fdr_bh
     205 study items associated with significant GO IDs (enriched)
       9 study items associated with significant GO IDs (purified)

Runing MF Ontology Analysis: current study set of 284 IDs.
 98%    277 of    284 study items found in association
100%    284 of    284 study items found in population(21965)
Calculating 4,565 uncorrected p-values using fisher_scipy_stats
   4,565 terms are associated with 18,703 of 21,965 population items
     598 terms are associated with    277 of    284 study items
  METHOD fdr_bh:
      31 GO terms found significant (< 0.05=alpha) ( 30 enriched +   1 purified): statsmodels fdr_bh
     215 study items associated with significant GO IDs (enriched)
      24 study items associated with significant GO IDs (purified)
  18877 items WROTE: upstream_750_score_900
go-basic.obo: fmt(1.2) rel(2024-01-17) 45,869 Terms

Load BP Ontology Enrichment Analysis ...
 85% 18,620 of 21,965 population items found in association

Load CC Ontology Enrichment Analysis ...
 85% 18,761 of 21,965 population items found in association

Load MF Ontology Enrichment Analysis ...
 85% 18,703 of 21,965 population items found in association

Runing BP Ontology Analysis: current study set of 282 IDs.
 96%    272 of    282 study items found in association
100%    282 of    282 study items found in population(21965)
Calculating 12,503 uncorrected p-values using fisher_scipy_stats
  12,503 terms are associated with 18,612 of 21,965 population items
   2,347 terms are associated with    272 of    282 study items
  METHOD fdr_bh:
      61 GO terms found significant (< 0.05=alpha) ( 60 enriched +   1 purified): statsmodels fdr_bh
     172 study items associated with significant GO IDs (enriched)
      13 study items associated with significant GO IDs (purified)

Runing CC Ontology Analysis: current study set of 282 IDs.
 98%    276 of    282 study items found in association
100%    282 of    282 study items found in population(21965)
Calculating 1,809 uncorrected p-values using fisher_scipy_stats
   1,809 terms are associated with 18,761 of 21,965 population items
     334 terms are associated with    276 of    282 study items
  METHOD fdr_bh:
      24 GO terms found significant (< 0.05=alpha) ( 23 enriched +   1 purified): statsmodels fdr_bh
     229 study items associated with significant GO IDs (enriched)
       9 study items associated with significant GO IDs (purified)

Runing MF Ontology Analysis: current study set of 282 IDs.
 98%    277 of    282 study items found in association
100%    282 of    282 study items found in population(21965)
Calculating 4,565 uncorrected p-values using fisher_scipy_stats
   4,565 terms are associated with 18,703 of 21,965 population items
     597 terms are associated with    277 of    282 study items
  METHOD fdr_bh:
      29 GO terms found significant (< 0.05=alpha) ( 28 enriched +   1 purified): statsmodels fdr_bh
     212 study items associated with significant GO IDs (enriched)
      22 study items associated with significant GO IDs (purified)
  18877 items WROTE: upstream_5000_score_950
go-basic.obo: fmt(1.2) rel(2024-01-17) 45,869 Terms

Load BP Ontology Enrichment Analysis ...
 85% 18,620 of 21,965 population items found in association

Load CC Ontology Enrichment Analysis ...
 85% 18,761 of 21,965 population items found in association

Load MF Ontology Enrichment Analysis ...
 85% 18,703 of 21,965 population items found in association

Runing BP Ontology Analysis: current study set of 62 IDs.
 98%     61 of     62 study items found in association
100%     62 of     62 study items found in population(21965)
Calculating 12,503 uncorrected p-values using fisher_scipy_stats
  12,503 terms are associated with 18,612 of 21,965 population items
     952 terms are associated with     61 of     62 study items
  METHOD fdr_bh:
       0 GO terms found significant (< 0.05=alpha) (  0 enriched +   0 purified): statsmodels fdr_bh
       0 study items associated with significant GO IDs (enriched)
       0 study items associated with significant GO IDs (purified)

Runing CC Ontology Analysis: current study set of 62 IDs.
100%     62 of     62 study items found in association
100%     62 of     62 study items found in population(21965)
Calculating 1,809 uncorrected p-values using fisher_scipy_stats
   1,809 terms are associated with 18,761 of 21,965 population items
     155 terms are associated with     62 of     62 study items
  METHOD fdr_bh:
       0 GO terms found significant (< 0.05=alpha) (  0 enriched +   0 purified): statsmodels fdr_bh
       0 study items associated with significant GO IDs (enriched)
       0 study items associated with significant GO IDs (purified)

Runing MF Ontology Analysis: current study set of 62 IDs.
 98%     61 of     62 study items found in association
100%     62 of     62 study items found in population(21965)
Calculating 4,565 uncorrected p-values using fisher_scipy_stats
   4,565 terms are associated with 18,703 of 21,965 population items
     274 terms are associated with     61 of     62 study items
  METHOD fdr_bh:
       0 GO terms found significant (< 0.05=alpha) (  0 enriched +   0 purified): statsmodels fdr_bh
       0 study items associated with significant GO IDs (enriched)
       0 study items associated with significant GO IDs (purified)
  18877 items WROTE: upstream_2500_score_990
go-basic.obo: fmt(1.2) rel(2024-01-17) 45,869 Terms

Load BP Ontology Enrichment Analysis ...
 85% 18,620 of 21,965 population items found in association

Load CC Ontology Enrichment Analysis ...
 85% 18,761 of 21,965 population items found in association

Load MF Ontology Enrichment Analysis ...
 85% 18,703 of 21,965 population items found in association

Runing BP Ontology Analysis: current study set of 312 IDs.
 96%    301 of    312 study items found in association
100%    312 of    312 study items found in population(21965)
Calculating 12,503 uncorrected p-values using fisher_scipy_stats
  12,503 terms are associated with 18,612 of 21,965 population items
   2,453 terms are associated with    301 of    312 study items
  METHOD fdr_bh:
      74 GO terms found significant (< 0.05=alpha) ( 73 enriched +   1 purified): statsmodels fdr_bh
     185 study items associated with significant GO IDs (enriched)
      15 study items associated with significant GO IDs (purified)

Runing CC Ontology Analysis: current study set of 312 IDs.
 97%    303 of    312 study items found in association
100%    312 of    312 study items found in population(21965)
Calculating 1,809 uncorrected p-values using fisher_scipy_stats
   1,809 terms are associated with 18,761 of 21,965 population items
     342 terms are associated with    303 of    312 study items
  METHOD fdr_bh:
      27 GO terms found significant (< 0.05=alpha) ( 26 enriched +   1 purified): statsmodels fdr_bh
     223 study items associated with significant GO IDs (enriched)
      10 study items associated with significant GO IDs (purified)

Runing MF Ontology Analysis: current study set of 312 IDs.
 97%    304 of    312 study items found in association
100%    312 of    312 study items found in population(21965)
Calculating 4,565 uncorrected p-values using fisher_scipy_stats
   4,565 terms are associated with 18,703 of 21,965 population items
     623 terms are associated with    304 of    312 study items
  METHOD fdr_bh:
      35 GO terms found significant (< 0.05=alpha) ( 34 enriched +   1 purified): statsmodels fdr_bh
     236 study items associated with significant GO IDs (enriched)
      25 study items associated with significant GO IDs (purified)
  18877 items WROTE: upstream_5000_score_900
go-basic.obo: fmt(1.2) rel(2024-01-17) 45,869 Terms

Load BP Ontology Enrichment Analysis ...
 85% 18,620 of 21,965 population items found in association

Load CC Ontology Enrichment Analysis ...
 85% 18,761 of 21,965 population items found in association

Load MF Ontology Enrichment Analysis ...
 85% 18,703 of 21,965 population items found in association

Runing BP Ontology Analysis: current study set of 35 IDs.
 97%     34 of     35 study items found in association
100%     35 of     35 study items found in population(21965)
Calculating 12,503 uncorrected p-values using fisher_scipy_stats
  12,503 terms are associated with 18,612 of 21,965 population items
     562 terms are associated with     34 of     35 study items
  METHOD fdr_bh:
       0 GO terms found significant (< 0.05=alpha) (  0 enriched +   0 purified): statsmodels fdr_bh
       0 study items associated with significant GO IDs (enriched)
       0 study items associated with significant GO IDs (purified)

Runing CC Ontology Analysis: current study set of 35 IDs.
100%     35 of     35 study items found in association
100%     35 of     35 study items found in population(21965)
Calculating 1,809 uncorrected p-values using fisher_scipy_stats
   1,809 terms are associated with 18,761 of 21,965 population items
     112 terms are associated with     35 of     35 study items
  METHOD fdr_bh:
       0 GO terms found significant (< 0.05=alpha) (  0 enriched +   0 purified): statsmodels fdr_bh
       0 study items associated with significant GO IDs (enriched)
       0 study items associated with significant GO IDs (purified)

Runing MF Ontology Analysis: current study set of 35 IDs.
100%     35 of     35 study items found in association
100%     35 of     35 study items found in population(21965)
Calculating 4,565 uncorrected p-values using fisher_scipy_stats
   4,565 terms are associated with 18,703 of 21,965 population items
     196 terms are associated with     35 of     35 study items
  METHOD fdr_bh:
       0 GO terms found significant (< 0.05=alpha) (  0 enriched +   0 purified): statsmodels fdr_bh
       0 study items associated with significant GO IDs (enriched)
       0 study items associated with significant GO IDs (purified)
  18877 items WROTE: upstream_750_score_990
go-basic.obo: fmt(1.2) rel(2024-01-17) 45,869 Terms

Load BP Ontology Enrichment Analysis ...
 85% 18,620 of 21,965 population items found in association

Load CC Ontology Enrichment Analysis ...
 85% 18,761 of 21,965 population items found in association

Load MF Ontology Enrichment Analysis ...
 85% 18,703 of 21,965 population items found in association

Runing BP Ontology Analysis: current study set of 181 IDs.
 97%    176 of    181 study items found in association
100%    181 of    181 study items found in population(21965)
Calculating 12,503 uncorrected p-values using fisher_scipy_stats
  12,503 terms are associated with 18,612 of 21,965 population items
   1,738 terms are associated with    176 of    181 study items
  METHOD fdr_bh:
      31 GO terms found significant (< 0.05=alpha) ( 31 enriched +   0 purified): statsmodels fdr_bh
      97 study items associated with significant GO IDs (enriched)
       0 study items associated with significant GO IDs (purified)

Runing CC Ontology Analysis: current study set of 181 IDs.
 99%    179 of    181 study items found in association
100%    181 of    181 study items found in population(21965)
Calculating 1,809 uncorrected p-values using fisher_scipy_stats
   1,809 terms are associated with 18,761 of 21,965 population items
     272 terms are associated with    179 of    181 study items
  METHOD fdr_bh:
      19 GO terms found significant (< 0.05=alpha) ( 18 enriched +   1 purified): statsmodels fdr_bh
      80 study items associated with significant GO IDs (enriched)
       4 study items associated with significant GO IDs (purified)

Runing MF Ontology Analysis: current study set of 181 IDs.
 99%    179 of    181 study items found in association
100%    181 of    181 study items found in population(21965)
Calculating 4,565 uncorrected p-values using fisher_scipy_stats
   4,565 terms are associated with 18,703 of 21,965 population items
     467 terms are associated with    179 of    181 study items
  METHOD fdr_bh:
      12 GO terms found significant (< 0.05=alpha) ( 12 enriched +   0 purified): statsmodels fdr_bh
     133 study items associated with significant GO IDs (enriched)
       0 study items associated with significant GO IDs (purified)
  18877 items WROTE: upstream_750_score_950
go-basic.obo: fmt(1.2) rel(2024-01-17) 45,869 Terms

Load BP Ontology Enrichment Analysis ...
 85% 18,620 of 21,965 population items found in association

Load CC Ontology Enrichment Analysis ...
 85% 18,761 of 21,965 population items found in association

Load MF Ontology Enrichment Analysis ...
 85% 18,703 of 21,965 population items found in association

Runing BP Ontology Analysis: current study set of 309 IDs.
 96%    298 of    309 study items found in association
100%    309 of    309 study items found in population(21965)
Calculating 12,503 uncorrected p-values using fisher_scipy_stats
  12,503 terms are associated with 18,612 of 21,965 population items
   2,445 terms are associated with    298 of    309 study items
  METHOD fdr_bh:
      78 GO terms found significant (< 0.05=alpha) ( 77 enriched +   1 purified): statsmodels fdr_bh
     189 study items associated with significant GO IDs (enriched)
      15 study items associated with significant GO IDs (purified)

Runing CC Ontology Analysis: current study set of 309 IDs.
 97%    300 of    309 study items found in association
100%    309 of    309 study items found in population(21965)
Calculating 1,809 uncorrected p-values using fisher_scipy_stats
   1,809 terms are associated with 18,761 of 21,965 population items
     341 terms are associated with    300 of    309 study items
  METHOD fdr_bh:
      26 GO terms found significant (< 0.05=alpha) ( 25 enriched +   1 purified): statsmodels fdr_bh
     219 study items associated with significant GO IDs (enriched)
      10 study items associated with significant GO IDs (purified)

Runing MF Ontology Analysis: current study set of 309 IDs.
 97%    301 of    309 study items found in association

## Concatenate All Significant Results Across Parameter Iterations

In [6]:
concat_df = []

for file in glob.glob("upstream_*"): 
    tmp_df = pd.read_csv(file, sep="\t")
    
    tmp_df["Param Combo"] = file
    
    concat_df.append(tmp_df[(tmp_df["p_fdr_bh"]<0.05) & (tmp_df["study_count"]>=4)])
    
    os.remove(file)

concat_df = pd.concat(concat_df)
concat_df.head()

,# GO,NS,enrichment,name,ratio_in_study,ratio_in_pop,p_uncorrected,depth,study_count,p_fdr_bh,study_items,Param Combo
0,GO:0008203,BP,e,cholesterol metabolic process,22/284,116/21965,1.177710e-19,6,22,1.472491e-15,"abca1, apoa1, apoa2, apob, apoe, cubn, cyp27a1, cyp51, dhcr24, dhcr7, fdft1, fdx1, hmgcs1, hnf1a, insig1, ldlr, mttp, mvk, nsdhl, sqle, srebf2, tm7sf2",upstream_750_score_900
1,GO:0008202,BP,e,steroid metabolic process,18/284,127/21965,5.479940e-14,4,18,3.425784e-10,"akr1c19, apoa1, apob, cubn, cyp27a1, cyp51, dhcr24, dhcr7, fdft1, fdx1, hmgcs1, insig1, ldlr, mttp, mvk, nsdhl, srebf2, tm7sf2",upstream_750_score_900
2,GO:0042632,BP,e,cholesterol homeostasis,16/284,99/21965,1.727625e-13,5,16,7.200165e-10,"abca1, apoa1, apoa2, apob, apoe, fabp4, fgfr4, gramd1b, hnf4a, insig1, ldlr, lpl, mttp, nr5a2, rora, srebf2",upstream_750_score_900
3,GO:0016126,BP,e,sterol biosynthetic process,10/284,29/21965,1.797797e-12,6,10,5.619465e-09,"cyp51, dhcr24, dhcr7, fdft1, hmgcs1, insig1, mvk, nsdhl, sqle, tm7sf2",upstream_750_score_900
4,GO:0006629,BP,e,lipid metabolic process,35/284,714/21965,1.423814e-11,3,35,3.560390e-08,"acly, aldh1a1, apoa1, apob, apoe, b4galt6, cubn, cyp26b1, cyp27a1, cyp51, dhcr24, dhcr7, elovl5, elovl6, fads2, fasn, fdft1, fdx1, gstm1, hmgcs1, hnf4a, insig1, ldlr, lpl, mttp, mvk, nsdhl, pip4k2b, plcd3, prkag3, scd2, sqle, srebf2, tecrl, tm7sf2",upstream_750_score_900

## Output Data

`GO` Enrichments

In [7]:
# GO enrichments
concat_df.to_csv("../outputs/sox4_target_genes_GO_enrichment_fdr_0.05_input_gene_greater_equal_4.csv", index=False)

Frequency of `GO` Terms

In [8]:
frequency = pd.DataFrame(concat_df[["name"]].value_counts()).reset_index()
frequency.columns=["GO Name", "Found in # of parameter combinations (OUT OF 9)"]

frequency.to_csv("../outputs/sox4_target_genes_most_common_enriched_pathways_fdr_0.05_input_gene_greater_equal_4.csv", index=False)

frequency.head()

,GO Name,Found in # of parameter combinations (OUT OF 9)
0,cholesterol biosynthetic process,7
1,steroid metabolic process,7
2,cholesterol homeostasis,7
3,axon,7
4,endoplasmic reticulum,7

`Sox4` Target Gene Lists

In [9]:
concat_sox4_target_list = []

for param_combo in sox4_target_dict: 
    tmp_df = pd.DataFrame()
    tmp_df["Genes"] = sox4_target_dict[param_combo] 
    tmp_df["Parameter Combination"] = param_combo
    
    concat_sox4_target_list.append(tmp_df)

concat_sox4_target_list = pd.concat(concat_sox4_target_list).sort_values(by=["Parameter Combination"])

concat_sox4_target_list.to_csv("../outputs/sox4_target_genes.csv", index=False)

concat_sox4_target_list

             Genes    Parameter Combination
308          dchs2  upstream_2500_score_900
129          svep1  upstream_2500_score_900
128            tnc  upstream_2500_score_900
127           ccn1  upstream_2500_score_900
126           mttp  upstream_2500_score_900
125        slc35a3  upstream_2500_score_900
124          crct1  upstream_2500_score_900
123         tm4sf1  upstream_2500_score_900
122           car3  upstream_2500_score_900
121           gnas  upstream_2500_score_900
120            ttl  upstream_2500_score_900
119         adam33  upstream_2500_score_900
118          map1a  upstream_2500_score_900
117            mdk  upstream_2500_score_900
116        creb3l1  upstream_2500_score_900
115           tfpi  upstream_2500_score_900
130          astn2  upstream_2500_score_900
114           lhx3  upstream_2500_score_900
131          ephb2  upstream_2500_score_900
133           nppb  upstream_2500_score_900
148           sspn  upstream_2500_score_900
147          grip2  upstream_2500_score_900
146        aldh1l1  upstream_2500_score_900
145          wdr54  upstream_2500_score_900
144        adamts9  upstream_2500_score_900
143         pcyox1  upstream_2500_score_900
142          gfpt1  upstream_2500_score_900
141           aoc1  upstream_2500_score_900
140          medag  upstream_2500_score_900
139          hnf1a  upstream_2500_score_900
138            pf4  upstream_2500_score_900
137           spp1  upstream_2500_score_900
136            klb  upstream_2500_score_900
135          fosl2  upstream_2500_score_900
134        ppp2r2c  upstream_2500_score_900
132        tnfrsf9  upstream_2500_score_900
113          nacc2  upstream_2500_score_900
112         col5a1  upstream_2500_score_900
111           cubn  upstream_2500_score_900
90            hhex  upstream_2500_score_900
89           pcgf5  upstream_2500_score_900
88          ankrd1  upstream_2500_score_900
87          tm7sf2  upstream_2500_score_900
86           lipo3  upstream_2500_score_900
85           fads2  upstream_2500_score_900
84           lims2  upstream_2500_score_900
83            apom  upstream_2500_score_900
82             xdh  upstream_2500_score_900
81           vegfa  upstream_2500_score_900
80       tnfrsf12a  upstream_2500_score_900
79            noct  upstream_2500_score_900
78           nr4a1  upstream_2500_score_900
77           clic6  upstream_2500_score_900
75           robo1  upstream_2500_score_900
91            fasn  upstream_2500_score_900
92            cpn1  upstream_2500_score_900
93            scd2  upstream_2500_score_900
94            sat1  upstream_2500_score_900
110           atf3  upstream_2500_score_900
109         tagln2  upstream_2500_score_900
108          lamc1  upstream_2500_score_900
107          rgs16  upstream_2500_score_900
106         pfkfb2  upstream_2500_score_900
105        cacna1s  upstream_2500_score_900
104          nr5a2  upstream_2500_score_900
149           gipr  upstream_2500_score_900
103        lrrfip1  upstream_2500_score_900
101  2810459m11rik  upstream_2500_score_900
100        cyp27a1  upstream_2500_score_900
99           il1r2  upstream_2500_score_900
98           il1r1  upstream_2500_score_900
97          col3a1  upstream_2500_score_900
96          fam20c  upstream_2500_score_900
95           itih5  upstream_2500_score_900
102           mlph  upstream_2500_score_900
150          nr2f2  upstream_2500_score_900
151            maz  upstream_2500_score_900
152         coro1a  upstream_2500_score_900
206          isg20  upstream_2500_score_900
205        mycbpap  upstream_2500_score_900
204         mvb12b  upstream_2500_score_900
203          hoxb5  upstream_2500_score_900
202          hoxb4  upstream_2500_score_900
201            sct  upstream_2500_score_900
200          ciart  upstream_2500_score_900
199         setd1b  upstream_2500_score_900
198        spats2l  upstream_2500_score_900
197         fkbp14  upstream_2500_score_900
196          dusp8  upstream_2500_score_900
195         abhd18  upstream_2500_score_900
194           erv3  upstream_2500_score_900
193          rims2  upstream_2500_score_900
192            psd  upstream_2500_score_900
207        gramd1b  upstream_2500_score_900
208           maob  upstream_2500_score_900
209          foxa3  upstream_2500_score_900
210          kcnd3  upstream_2500_score_900
226           hic1  upstream_2500_score_900
225          synpo  upstream_2500_score_900
224         ccdc63  upstream_2500_score_900
223      serpinb6b  upstream_2500_score_900
222           maff  upstream_2500_score_900
221           reln  upstream_2500_score_900
220          hoxd1  upstream_2500_score_900
191          foxa2  upstream_2500_score_900
219          itga1  upstream_2500_score_900
217        fam222a  upstream_2500_score_900
216          kcnj2  upstream_2500_score_900
215          hspb8  upstream_2500_score_900
214         elovl6  upstream_2500_score_900
213          pde9a  upstream_2500_score_900
212           fzd7  upstream_2500_score_900
211         atp1a3  upstream_2500_score_900
218            mvk  upstream_2500_score_900
74           abcc5  upstream_2500_score_900
190         tmem71  upstream_2500_score_900
188           wnt4  upstream_2500_score_900
167           fdx1  upstream_2500_score_900
166        nectin1  upstream_2500_score_900
165          acta1  upstream_2500_score_900
164           car7  upstream_2500_score_900
163           nkd1  upstream_2500_score_900
162          cbln1  upstream_2500_score_900
161          sfrp1  upstream_2500_score_900
160            bgn  upstream_2500_score_900
159          nsdhl  upstream_2500_score_900
158          sytl4  upstream_2500_score_900
157          efnb1  upstream_2500_score_900
156           elf4  upstream_2500_score_900
155           ano1  upstream_2500_score_900
154           plk1  upstream_2500_score_900
153          fgfr2  upstream_2500_score_900
168  2310030g06rik  upstream_2500_score_900
169          apoa1  upstream_2500_score_900
170           ldlr  upstream_2500_score_900
171           rora  upstream_2500_score_900
187          ttyh3  upstream_2500_score_900
186         zfp983  upstream_2500_score_900
185          tdrd7  upstream_2500_score_900
184           crb2  upstream_2500_score_900
183         nfkbiz  upstream_2500_score_900
182          atcay  upstream_2500_score_900
181         dhcr24  upstream_2500_score_900
189          smad6  upstream_2500_score_900
180           gulo  upstream_2500_score_900
178          rxfp1  upstream_2500_score_900
177          calm4  upstream_2500_score_900
176         rbfox2  upstream_2500_score_900
175          lama1  upstream_2500_score_900
174          ephb1  upstream_2500_score_900
173         elovl5  upstream_2500_score_900
172           hcn4  upstream_2500_score_900
179          kctd9  upstream_2500_score_900
73            psca  upstream_2500_score_900
76           dop1b  upstream_2500_score_900
71          fbxo32  upstream_2500_score_900
253          amer1  upstream_2500_score_900
254           adnp  upstream_2500_score_900
255           eml5  upstream_2500_score_900
256          flrt3  upstream_2500_score_900
257          lrrc3  upstream_2500_score_900
258         hbb-bs  upstream_2500_score_900
259          actn2  upstream_2500_score_900
260          robo2  upstream_2500_score_900
261            jun  upstream_2500_score_900
262          map1b  upstream_2500_score_900
263         mllt11  upstream_2500_score_900
264       arhgap20  upstream_2500_score_900
265        aldh1a1  upstream_2500_score_900
266           emcn  upstream_2500_score_900
267          fsd1l  upstream_2500_score_900
252        rasl11b  upstream_2500_score_900
251          nlrc3  upstream_2500_score_900
250         zbtb12  upstream_2500_score_900
249         tmsb4x  upstream_2500_score_900
72          srebf2  upstream_2500_score_900
234         insig1  upstream_2500_score_900
235        onecut3  upstream_2500_score_900
236          npas4  upstream_2500_score_900
237        onecut2  upstream_2500_score_900
238         sprr2h  upstream_2500_score_900
239          prr12  upstream_2500_score_900
268        tmem158  upstream_2500_score_900
240        slitrk4  upstream_2500_score_900
242          tenm4  upstream_2500_score_900
243         col6a3  upstream_2500_score_900
244         crebrf  upstream_2500_score_900
245           pdp2  upstream_2500_score_900
246           igf2  upstream_2500_score_900
247          tecrl  upstream_2500_score_900
248        zfp280b  upstream_2500_score_900
241          frat2  upstream_2500_score_900
232         shisa2  upstream_2500_score_900
269          nell1  upstream_2500_score_900
271           prr9  upstream_2500_score_900
292         lgals1  upstream_2500_score_900
293          nr2f1  upstream_2500_score_900
294           lyz2  upstream_2500_score_900
295          ctcfl  upstream_2500_score_900
296        akr1c19  upstream_2500_score_900
297          h2-q6  upstream_2500_score_900
298          kcng1  upstream_2500_score_900
299          myh7b  upstream_2500_score_900
300           bhmt  upstream_2500_score_900
301           sox4  upstream_2500_score_900
302           fyb2  upstream_2500_score_900
303          prrt4  upstream_2500_score_900
304          ulbp1  upstream_2500_score_900
305         hmgcs1  upstream_2500_score_900
306           h1f0  upstream_2500_score_900
291        ppp1r3c  upstream_2500_score_900
290          frat1  upstream_2500_score_900
289          paqr9  upstream_2500_score_900
288        cyp26b1  upstream_2500_score_900
272          slit3  upstream_2500_score_900
273          usp13  upstream_2500_score_900
274            ado  upstream_2500_score_900
275          lmcd1  upstream_2500_score_900
276        mab21l2  upstream_2500_score_900
277          gstm1  upstream_2500_score_900
278          dhcr7  upstream_2500_score_900
270        b4galt6  upstream_2500_score_900
279         rnf207  upstream_2500_score_900
281         adgrg3  upstream_2500_score_900
282          samd5  upstream_2500_score_900
283           rrs1  upstream_2500_score_900
284          hipk2  upstream_2500_score_900
285          fabp4  upstream_2500_score_900
286          actg1  upstream_2500_score_900
287           nrg1  upstream_2500_score_900
280          nptx2  upstream_2500_score_900
231          lacc1  upstream_2500_score_900
233          h1f10  upstream_2500_score_900
229         s100a1  upstream_2500_score_900
50          lratd1  upstream_2500_score_900
49         galnt10  upstream_2500_score_900
48           ptprb  upstream_2500_score_900
47           hkdc1  upstream_2500_score_900
46           timp3  upstream_2500_score_900
45            ccn2  upstream_2500_score_900
44         sec14l4  upstream_2500_score_900
43            aoc3  upstream_2500_score_900
42           myh11  upstream_2500_score_900
41           sfrp5  upstream_2500_score_900
40            tbx3  upstream_2500_score_900
39         pip4k2b  upstream_2500_score_900
38          prl8a2  upstream_2500_score_900
230          pcsk9  upstream_2500_score_900
36            etv4  upstream_2500_score_900
51            apob  upstream_2500_score_900
52           rsad2  upstream_2500_score_900
53           hnf1b  upstream_2500_score_900
54           krt19  upstream_2500_score_900
70            sqle  upstream_2500_score_900
69         retreg1  upstream_2500_score_900
68           mbnl2  upstream_2500_score_900
67           stmn4  upstream_2500_score_900
66            rgcc  upstream_2500_score_900
65             fst  upstream_2500_score_900
64            hcn1  upstream_2500_score_900
35            wsb1  upstream_2500_score_900
63       serpinb9c  upstream_2500_score_900
61           sfrp4  upstream_2500_score_900
60            amph  upstream_2500_score_900
59            ryr2  upstream_2500_score_900
58           fdft1  upstream_2500_score_900
57          ppp4r4  upstream_2500_score_900
56           plcd3  upstream_2500_score_900
55            acly  upstream_2500_score_900
62            edn1  upstream_2500_score_900
34           stac2  upstream_2500_score_900
37           hnf4a  upstream_2500_score_900
32          celsr1  upstream_2500_score_900
11            apoe  upstream_2500_score_900
33             vtn  upstream_2500_score_900
9            stat6  upstream_2500_score_900
8              vwf  upstream_2500_score_900
7              ddt  upstream_2500_score_900
6            gstt1  upstream_2500_score_900
5            cyp51  upstream_2500_score_900
4             car4  upstream_2500_score_900
3            pdgfb  upstream_2500_score_900
2           alox12  upstream_2500_score_900
1            axin2  upstream_2500_score_900
0             tbx2  upstream_2500_score_900
307           bin2  upstream_2500_score_900
227          kcnj6  upstream_2500_score_900
228        irf2bp1  upstream_2500_score_900
12            ier3  upstream_2500_score_900
13            eno2  upstream_2500_score_900
10           nr2f6  upstream_2500_score_900
15           fgfr4  upstream_2500_score_900
31             lpl  upstream_2500_score_900
30         gadd45b  upstream_2500_score_900
29           abca1  upstream_2500_score_900
28            stc1  upstream_2500_score_900
14           nmrk2  upstream_2500_score_900
26            wnt2  upstream_2500_score_900
25            epn3  upstream_2500_score_900
24         hnrnpa0  upstream_2500_score_900
27             blk  upstream_2500_score_900
22          prkag3  upstream_2500_score_900
21           epha2  upstream_2500_score_900
20           cdc20  upstream_2500_score_900
19         cbfa2t3  upstream_2500_score_900
18           gata6  upstream_2500_score_900
17           apoa2  upstream_2500_score_900
16           cadm3  upstream_2500_score_900
23           snai3  upstream_2500_score_900
238          kcng1  upstream_2500_score_950
244           bin2  upstream_2500_score_950
243           h1f0  upstream_2500_score_950
242         hmgcs1  upstream_2500_score_950
241          ulbp1  upstream_2500_score_950
240          prrt4  upstream_2500_score_950
239           bhmt  upstream_2500_score_950
237        akr1c19  upstream_2500_score_950
226         adgrg3  upstream_2500_score_950
235          nr2f1  upstream_2500_score_950
84         cacna1s  upstream_2500_score_950
83           nr5a2  upstream_2500_score_950
82         lrrfip1  upstream_2500_score_950
81   2810459m11rik  upstream_2500_score_950
80         cyp27a1  upstream_2500_score_950
79           il1r2  upstream_2500_score_950
78           il1r1  upstream_2500_score_950
77          col3a1  upstream_2500_score_950
76          fam20c  upstream_2500_score_950
75            sat1  upstream_2500_score_950
74            scd2  upstream_2500_score_950
73            cpn1  upstream_2500_score_950
72            fasn  upstream_2500_score_950
71           pcgf5  upstream_2500_score_950
70          ankrd1  upstream_2500_score_950
69          tm7sf2  upstream_2500_score_950
68           lipo3  upstream_2500_score_950
67           fads2  upstream_2500_score_950
66           lims2  upstream_2500_score_950
65            apom  upstream_2500_score_950
64             xdh  upstream_2500_score_950
63           vegfa  upstream_2500_score_950
62       tnfrsf12a  upstream_2500_score_950
61            noct  upstream_2500_score_950
60           nr4a1  upstream_2500_score_950
85          pfkfb2  upstream_2500_score_950
86           lamc1  upstream_2500_score_950
236          ctcfl  upstream_2500_score_950
88            atf3  upstream_2500_score_950
114          gfpt1  upstream_2500_score_950
113           aoc1  upstream_2500_score_950
112          hnf1a  upstream_2500_score_950
111            pf4  upstream_2500_score_950
110           spp1  upstream_2500_score_950
109          fosl2  upstream_2500_score_950
108        ppp2r2c  upstream_2500_score_950
107        tnfrsf9  upstream_2500_score_950
106          ephb2  upstream_2500_score_950
105          astn2  upstream_2500_score_950
104          svep1  upstream_2500_score_950
103            tnc  upstream_2500_score_950
59           clic6  upstream_2500_score_950
102           ccn1  upstream_2500_score_950
100         tm4sf1  upstream_2500_score_950
99            car3  upstream_2500_score_950
98            gnas  upstream_2500_score_950
97             ttl  upstream_2500_score_950
96          adam33  upstream_2500_score_950
95           map1a  upstream_2500_score_950
94             mdk  upstream_2500_score_950
93         creb3l1  upstream_2500_score_950
92            tfpi  upstream_2500_score_950
91           nacc2  upstream_2500_score_950
90          col5a1  upstream_2500_score_950
89            cubn  upstream_2500_score_950
101           mttp  upstream_2500_score_950
58           dop1b  upstream_2500_score_950
57           robo1  upstream_2500_score_950
56           abcc5  upstream_2500_score_950
25            wsb1  upstream_2500_score_950
24           stac2  upstream_2500_score_950
23             vtn  upstream_2500_score_950
22          celsr1  upstream_2500_score_950
21             lpl  upstream_2500_score_950
20         gadd45b  upstream_2500_score_950
19           abca1  upstream_2500_score_950
18            stc1  upstream_2500_score_950
17             blk  upstream_2500_score_950
16            epn3  upstream_2500_score_950
15          prkag3  upstream_2500_score_950
14           cdc20  upstream_2500_score_950
26            etv4  upstream_2500_score_950
13         cbfa2t3  upstream_2500_score_950
11           cadm3  upstream_2500_score_950
10           fgfr4  upstream_2500_score_950
9            nmrk2  upstream_2500_score_950
8             eno2  upstream_2500_score_950
7             ier3  upstream_2500_score_950
6             apoe  upstream_2500_score_950
5            nr2f6  upstream_2500_score_950
4            stat6  upstream_2500_score_950
3              vwf  upstream_2500_score_950
2              ddt  upstream_2500_score_950
1           alox12  upstream_2500_score_950
0            axin2  upstream_2500_score_950
12           gata6  upstream_2500_score_950
115         pcyox1  upstream_2500_score_950
27           hnf4a  upstream_2500_score_950
29         pip4k2b  upstream_2500_score_950
55            psca  upstream_2500_score_950
54          srebf2  upstream_2500_score_950
53          fbxo32  upstream_2500_score_950
52            sqle  upstream_2500_score_950
51         retreg1  upstream_2500_score_950
50           mbnl2  upstream_2500_score_950
49           stmn4  upstream_2500_score_950
48            rgcc  upstream_2500_score_950
47            hcn1  upstream_2500_score_950
46            edn1  upstream_2500_score_950
45            ryr2  upstream_2500_score_950
44           fdft1  upstream_2500_score_950
28          prl8a2  upstream_2500_score_950
43          ppp4r4  upstream_2500_score_950
41           hnf1b  upstream_2500_score_950
40           rsad2  upstream_2500_score_950
39            apob  upstream_2500_score_950
38          lratd1  upstream_2500_score_950
37         galnt10  upstream_2500_score_950
36           ptprb  upstream_2500_score_950
35           timp3  upstream_2500_score_950
34            ccn2  upstream_2500_score_950
33         sec14l4  upstream_2500_score_950
32           myh11  upstream_2500_score_950
31           sfrp5  upstream_2500_score_950
30            tbx3  upstream_2500_score_950
42            acly  upstream_2500_score_950
116        adamts9  upstream_2500_score_950
87          tagln2  upstream_2500_score_950
118        aldh1l1  upstream_2500_score_950
203          nlrc3  upstream_2500_score_950
202         zbtb12  upstream_2500_score_950
201         tmsb4x  upstream_2500_score_950
200          tecrl  upstream_2500_score_950
199           igf2  upstream_2500_score_950
198           pdp2  upstream_2500_score_950
197         crebrf  upstream_2500_score_950
196         col6a3  upstream_2500_score_950
195          tenm4  upstream_2500_score_950
194          frat2  upstream_2500_score_950
193          prr12  upstream_2500_score_950
192         sprr2h  upstream_2500_score_950
191        onecut2  upstream_2500_score_950
190          npas4  upstream_2500_score_950
189        onecut3  upstream_2500_score_950